services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wilisson/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wilisson/data/mariadb